openapi: 3.0.0
info:
  title: CHAMAlink API
  version: 1.0.0
  description: |-
    This is the official CHAMAlink API documentation. All endpoints are secured and require authentication unless otherwise stated.
servers:
  - url: https://api.chamalink.com
paths:
  /api/v1/webhooks/trigger:
    post:
      summary: Trigger a webhook event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                event:
                  type: string
                payload:
                  type: object
      responses:
        '200':
          description: Webhook triggered
  /api/v1/webhooks/register:
    post:
      summary: Register a new webhook endpoint
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                event:
                  type: string
      responses:
        '201':
          description: Webhook registered
