"""Add enterprise billing features

Revision ID: 070cc6bbc272
Revises: 207e2b37d538
Create Date: 2025-07-10 01:22:02.249297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '070cc6bbc272'
down_revision = '207e2b37d538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    billing_type_enum = sa.Enum('FIXED', 'PER_MEMBER', 'HYBRID', name='enterprisebillingtype')
    billing_type_enum.create(op.get_bind())
    
    with op.batch_alter_table('enterprise_subscription_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_type', billing_type_enum, nullable=True))
        batch_op.add_column(sa.Column('price_per_member', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('base_service_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('training_fee_per_day', sa.Float(), nullable=True))

    with op.batch_alter_table('enterprise_user_subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_member_limit', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_payment_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('service_fee_paid', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('training_days_purchased', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enterprise_user_subscriptions', schema=None) as batch_op:
        batch_op.drop_column('training_days_purchased')
        batch_op.drop_column('service_fee_paid')
        batch_op.drop_column('last_payment_amount')
        batch_op.drop_column('paid_member_limit')

    with op.batch_alter_table('enterprise_subscription_plans', schema=None) as batch_op:
        batch_op.drop_column('training_fee_per_day')
        batch_op.drop_column('base_service_fee')
        batch_op.drop_column('price_per_member')
        batch_op.drop_column('billing_type')
    
    # Drop the enum type
    billing_type_enum = sa.Enum('FIXED', 'PER_MEMBER', 'HYBRID', name='enterprisebillingtype')
    billing_type_enum.drop(op.get_bind())

    # ### end Alembic commands ###
