"""Ensure two_factor_codes table for 2FA

Revision ID: 32e8cc35544c
Revises: b6906a2f3b28
Create Date: 2025-08-03 16:02:23.633832

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '32e8cc35544c'
down_revision = 'b6906a2f3b28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('details', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('audit_logs_chama_id_fkey'), type_='foreignkey')
        batch_op.drop_column('user_agent')
        batch_op.drop_column('entity_type')
        batch_op.drop_column('old_values')
        batch_op.drop_column('action')
        batch_op.drop_column('chama_id')
        batch_op.drop_column('entity_id')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('new_values')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_values', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('entity_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('chama_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('action', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('old_values', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('audit_logs_chama_id_fkey'), 'chamas', ['chama_id'], ['id'])
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('details')
        batch_op.drop_column('event')

    # ### end Alembic commands ###
