"""Add enterprise subscription models

Revision ID: 3f04fb5e1e49
Revises: 2e7c611b71f5
Create Date: 2025-07-09 19:27:51.967340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f04fb5e1e49'
down_revision = '2e7c611b71f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enterprise_subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('plan_type', sa.Enum('BASIC', 'ADVANCED', 'ENTERPRISE', name='plantype'), nullable=False),
    sa.Column('price_monthly', sa.Float(), nullable=False),
    sa.Column('price_yearly', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('max_chamas', sa.Integer(), nullable=True),
    sa.Column('max_members_per_chama', sa.Integer(), nullable=True),
    sa.Column('max_loans_per_month', sa.Integer(), nullable=True),
    sa.Column('max_sms_per_month', sa.Integer(), nullable=True),
    sa.Column('max_file_uploads_mb', sa.Integer(), nullable=True),
    sa.Column('has_sms_notifications', sa.Boolean(), nullable=True),
    sa.Column('has_advanced_reporting', sa.Boolean(), nullable=True),
    sa.Column('has_bulk_operations', sa.Boolean(), nullable=True),
    sa.Column('has_api_access', sa.Boolean(), nullable=True),
    sa.Column('has_white_labeling', sa.Boolean(), nullable=True),
    sa.Column('has_priority_support', sa.Boolean(), nullable=True),
    sa.Column('has_audit_logs', sa.Boolean(), nullable=True),
    sa.Column('has_multi_signature', sa.Boolean(), nullable=True),
    sa.Column('has_automated_backups', sa.Boolean(), nullable=True),
    sa.Column('has_custom_branding', sa.Boolean(), nullable=True),
    sa.Column('has_dedicated_manager', sa.Boolean(), nullable=True),
    sa.Column('has_training_support', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enterprise_user_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('auto_renew', sa.Boolean(), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('last_payment_date', sa.DateTime(), nullable=True),
    sa.Column('next_payment_date', sa.DateTime(), nullable=True),
    sa.Column('payment_frequency', sa.String(length=10), nullable=True),
    sa.Column('current_chamas', sa.Integer(), nullable=True),
    sa.Column('current_members', sa.Integer(), nullable=True),
    sa.Column('monthly_loans', sa.Integer(), nullable=True),
    sa.Column('monthly_sms_sent', sa.Integer(), nullable=True),
    sa.Column('storage_used_mb', sa.Float(), nullable=True),
    sa.Column('custom_domain', sa.String(length=100), nullable=True),
    sa.Column('white_label_config', sa.JSON(), nullable=True),
    sa.Column('dedicated_manager_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dedicated_manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['enterprise_subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enterprise_subscription_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subscription_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('payment_reference', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('invoice_generated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['enterprise_user_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enterprise_subscription_payments')
    op.drop_table('enterprise_user_subscriptions')
    op.drop_table('enterprise_subscription_plans')
    # ### end Alembic commands ###
