"""Add registration fee to chamas and registration fee payments

Revision ID: 57b2bc2be1bb
Revises: 5295312b8471
Create Date: 2025-07-09 17:41:45.263457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57b2bc2be1bb'
down_revision = '5295312b8471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_fee_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('mpesa_receipt_number', sa.String(length=200), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chamas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_fee', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamas', schema=None) as batch_op:
        batch_op.drop_column('registration_fee')

    op.drop_table('registration_fee_payments')
    # ### end Alembic commands ###
