"""Add multi-signature transaction support

Revision ID: 63302c213eaf
Revises: 3f04fb5e1e49
Create Date: 2025-07-09 19:42:58.684472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63302c213eaf'
down_revision = '3f04fb5e1e49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multi_signature_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chama_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('transaction_reference_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('first_signatory_id', sa.Integer(), nullable=True),
    sa.Column('first_signature_at', sa.DateTime(), nullable=True),
    sa.Column('first_signature_comment', sa.Text(), nullable=True),
    sa.Column('second_signatory_id', sa.Integer(), nullable=True),
    sa.Column('second_signature_at', sa.DateTime(), nullable=True),
    sa.Column('second_signature_comment', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address_request', sa.String(length=45), nullable=True),
    sa.Column('ip_address_first_sign', sa.String(length=45), nullable=True),
    sa.Column('ip_address_second_sign', sa.String(length=45), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chama_id'], ['chamas.id'], ),
    sa.ForeignKeyConstraint(['first_signatory_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['second_signatory_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requires_multi_signature', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('multi_sig_transaction_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('disbursement_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('disbursement_details', sa.JSON(), nullable=True))
        batch_op.create_foreign_key(None, 'multi_signature_transactions', ['multi_sig_transaction_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('disbursement_details')
        batch_op.drop_column('disbursement_method')
        batch_op.drop_column('multi_sig_transaction_id')
        batch_op.drop_column('requires_multi_signature')

    op.drop_table('multi_signature_transactions')
    # ### end Alembic commands ###
