"""Add multi-currency and country support

Revision ID: bf927dfa1ec5
Revises: e549b01db3ae
Create Date: 2025-07-12 14:42:42.042188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf927dfa1ec5'
down_revision = 'e549b01db3ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chamas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_currency', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('multi_currency_enabled', sa.Boolean(), nullable=True))

    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('exchange_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('original_amount', sa.Float(), nullable=True))

    with op.batch_alter_table('loan_applications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('exchange_rate', sa.Float(), nullable=True))

    with op.batch_alter_table('loan_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('exchange_rate', sa.Float(), nullable=True))

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('exchange_rate', sa.Float(), nullable=True))

    with op.batch_alter_table('penalties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('exchange_rate', sa.Float(), nullable=True))

    with op.batch_alter_table('penalty_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('exchange_rate', sa.Float(), nullable=True))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('transaction_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('exchange_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('original_amount', sa.Float(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_currency', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('country_code', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('country_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('timezone')
        batch_op.drop_column('city')
        batch_op.drop_column('country_name')
        batch_op.drop_column('country_code')
        batch_op.drop_column('preferred_currency')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('original_amount')
        batch_op.drop_column('exchange_rate')
        batch_op.drop_column('currency')
        batch_op.drop_column('transaction_id')
        batch_op.drop_column('payment_method')

    with op.batch_alter_table('penalty_payments', schema=None) as batch_op:
        batch_op.drop_column('exchange_rate')
        batch_op.drop_column('currency')

    with op.batch_alter_table('penalties', schema=None) as batch_op:
        batch_op.drop_column('exchange_rate')
        batch_op.drop_column('currency')

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_column('exchange_rate')
        batch_op.drop_column('currency')

    with op.batch_alter_table('loan_payments', schema=None) as batch_op:
        batch_op.drop_column('exchange_rate')
        batch_op.drop_column('currency')

    with op.batch_alter_table('loan_applications', schema=None) as batch_op:
        batch_op.drop_column('exchange_rate')
        batch_op.drop_column('currency')

    with op.batch_alter_table('contributions', schema=None) as batch_op:
        batch_op.drop_column('original_amount')
        batch_op.drop_column('exchange_rate')
        batch_op.drop_column('currency')
        batch_op.drop_column('payment_method')

    with op.batch_alter_table('chamas', schema=None) as batch_op:
        batch_op.drop_column('multi_currency_enabled')
        batch_op.drop_column('base_currency')

    # ### end Alembic commands ###
