"""Add user preference fields

Revision ID: e549b01db3ae
Revises: 7d8f90a15bc2
Create Date: 2025-07-10 17:57:54.206637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e549b01db3ae'
down_revision = '7d8f90a15bc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_language', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('preferred_theme', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('preferred_font', sa.String(length=20), nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_password_reset_token'))
        batch_op.create_unique_constraint(None, ['password_reset_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_users_password_reset_token'), ['password_reset_token'], unique=True)
        batch_op.drop_column('preferred_font')
        batch_op.drop_column('preferred_theme')
        batch_op.drop_column('preferred_language')

    # ### end Alembic commands ###
