name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: chamalink_db
          POSTGRES_USER: chamalink_user
          POSTGRES_PASSWORD: changeme
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements-python311.txt
    - name: Run tests
      env:
        SQLALCHEMY_DATABASE_URI: postgresql://chamalink_user:changeme@localhost:5432/chamalink_db
      run: |
        pytest || echo 'No tests found.'
